language: clojure
before_install: echo $HOME
install:
- curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
- chmod +x linux-install-1.10.1.469.sh
- sudo ./linux-install-1.10.1.469.sh
- rm linux-install-1.10.1.469.sh
script: make build
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file: 'target/*'
  skip_cleanup: true
  draft: true
  on:
    repo: Aidbox/stresty
